### ISSUE TITLE
more help on compiler

### ISSUE THREAD

**Issue by Lewiscowles1986** [gingold-adacore/rpi3-fosdem17#1]
The only place I can find the compiler you are referencing is free-bsd. Could you please give a hint as to which system supports gcc with that package name?

**Comment by gingold-adacore** [comment]
On 19/04/2017 12:20, Lewis Cowles wrote:
> The only place I can find the compiler you are referencing is free-bsd.
> Could you please give a hint as to which system supports gcc with that
> package name?

You can use any aarch64 cross compiler.

In Ubuntu, its name looks to be gcc-aarch64-linux-gnu

Regards.
